//
//  DetailsViewController.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 17.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import UIKit

class DetailsViewController: BaseViewController {
    
    // MARK: - Outlets
    
    @IBOutlet weak var backgroundImageView: UIImageView!
    
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var degreeLabel: UILabel!
    @IBOutlet weak var unitLabel: UILabel!
    @IBOutlet weak var weatherLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var windLabel: UILabel!
    @IBOutlet weak var humidityLabel: UILabel!
    
    @IBOutlet weak var tableView: UITableView!

    // MARK: - Dependencies
    
    var presenter: DetailsPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.getFiveDaysWeather()
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
        if let currentWeather = presenter.getCurrentWeather() {
            self.nameLabel.text = currentWeather.name
            self.degreeLabel.text = "\(currentWeather.degree.description)"
            self.weatherLabel.text = currentWeather.weather
            self.descriptionLabel.text = currentWeather.description.capitalized
            self.windLabel.text = "\(currentWeather.wind.description)"
            self.humidityLabel.text = "\(currentWeather.humidity.description)"
            self.unitLabel.text = currentWeather.unit
            
            self.backgroundImageView.image = currentWeather.image
        }
    }
    
    // MARK: - Initialization
    
    // MARK: - Actions
    
}

// MARK: - Extensions

extension DetailsViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.getWeathersCount()
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)

        if let weather = presenter.getWeatherAt(index: indexPath.row) {
            
            if let dateString = weather.date?.split(separator: " ").first {
                cell.textLabel?.text = presenter.formatDate(dateString: String(dateString))
                cell.detailTextLabel?.text = "\(weather.degree.description)\(weather.unit.description)"
            }
        }
        return cell
    }
}

// MARK: - Protocol Implemantations

extension DetailsViewController: DetailsViewControllerProtocol {
    
    func reloadTableView() {
        tableView.reloadData()
    }
}
