//
//  DetailsInteractor.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 17.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import Foundation

class DetailsInteractor: BaseInteractor {
    
    // MARK: - Dependencies
    
    var presenter: DetailsPresenterInteractorProtocol!
    
    // MARK: - Initialization
    
    override init(networkService: NetworkService? = nil, coreDataService: CoreDataService? = nil) {
        super.init(networkService: networkService, coreDataService: coreDataService)
    }
    
    // MARK: - Business Logic

}

// MARK: - Extensions

// MARK: - Protocols Implemantations

extension DetailsInteractor: DetailsInteractorProtocol {
    
    func fetchFiveDaysWeather(location: Location) {
        
        let latitude = location.latitude
        let longitude = location.longitude
        
        var weatherArray = [WeatherModel]()
        
        if let languageCode = Locale.current.languageCode {
            let unit = UserDefaults.standard.string(forKey: "unit") ?? "metric"
            if let url = URL(string: NetworkConstants.forecast + "?lat=\(latitude)&lon=\(longitude)&units=\(unit)&lang=\(languageCode)&appid=" + NetworkConstants.apiKey) {
                
                networkService.getJSON(url: url, success: { (json) in
                    for weatherJSON in json["list"].arrayValue {
                        if weatherJSON["dt_txt"].stringValue.split(separator: " ")[1].starts(with: "12") {
                            weatherArray.append(WeatherModel(json: weatherJSON))
                        }
                    }
                    
                    self.presenter.setWeatherArray(weathers: weatherArray)
                }, failure: { (error) in
                    print(error)
                })
            }
        } 
    }
}
