//
//  DetailsWireframe.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 17.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import UIKit

class DetailsWireframe: BaseWireframe {
    
    func show(transitionType: WireframeTransitionType, delegate: DetailsPresenterDelegateProtocol? = nil, extras: DetailsExtras) {
        let viewController: DetailsViewController = UIStoryboard.home.instantiateViewController()
        
        let interactor = DetailsInteractor(networkService: NetworkService.sharedInstance)
        
        let presenter = DetailsPresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: viewController)
    }
    
}
