//
//  DetailsProtocols.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 17.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import UIKit

typealias DetailsExtras = (location: Location, weather: WeatherModel)

// MARK: - View Controller

protocol DetailsViewControllerProtocol: BaseViewControllerProtocol {
    
    func reloadTableView()
}

// MARK: - Presenter

protocol DetailsPresenterViewProtocol: BasePresenterViewProtocol {
    
    func getCurrentWeather() -> WeatherModel?
    func getFiveDaysWeather()
    func getWeathersCount() -> Int
    func getWeatherAt(index: Int) -> WeatherModel?
    func formatDate(dateString: String) -> String?
}

protocol DetailsPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func setWeatherArray(weathers: [WeatherModel])
}

protocol DetailsPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol DetailsInteractorProtocol: BaseInteractorProtocol {
    
    func fetchFiveDaysWeather(location: Location)
}
