//
//  HomeInteractor.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import Foundation
import Alamofire

class HomeInteractor: BaseInteractor {
    
    // MARK: - Dependencies
    
    var presenter: HomePresenterInteractorProtocol!
    
    // MARK: - Initialization
    
    override init(networkService: NetworkService? = nil, coreDataService: CoreDataService? = nil) {
        super.init(networkService: networkService, coreDataService: coreDataService)
    }
    
    // MARK: - Business Logic
}

// MARK: - Extnensions

// MARK: - Protocols Implemantations

extension HomeInteractor: HomeInteractorProtocol {
    
    func getCurrrentWeather(lat: Double, lon: Double) {
        if let languageCode = Locale.current.languageCode {
            if let weahterUnit = UserDefaults.standard.string(forKey: "unit") {
                if let url = URL(string: NetworkConstants.weather + "?lat=\(lat)&lon=\(lon)&units=\(weahterUnit)&lang=\(languageCode)&appid=" + NetworkConstants.apiKey) {
                
                    networkService.getJSON(url: url, success: { (json) in
                        self.presenter.setCurrentWeather(currentWeather: WeatherModel(json: json))
                        
                    }, failure: { (error) in
                        print(error)
                    })
                }
            }
        }
    }
}
