//
//  HomeProtocols.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import UIKit

// MARK: - View Controller

protocol HomeViewControllerProtocol: BaseViewControllerProtocol {
    
    func setCurrentWeatherLabel(currentWeather: WeatherModel)
}

// MARK: - Presenter

protocol HomePresenterViewProtocol: BasePresenterViewProtocol {
    
    func getCurrrentWeather(lat: Double, lon: Double)
}

protocol HomePresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func setCurrentWeather(currentWeather: WeatherModel)
}

protocol HomePresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol HomeInteractorProtocol: BaseInteractorProtocol {
    
    func getCurrrentWeather(lat: Double, lon: Double)
}
