//
//  HomeProtocols.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import UIKit

// MARK: - View Controller

protocol HomeViewControllerProtocol: BaseViewControllerProtocol {
    
    func setCurrentWeatherLabel(currentWeather: WeatherModel)
    func reloadTableView()
    func deleteTableRow(indexPaths: [IndexPath])
}

// MARK: - Presenter

protocol HomePresenterViewProtocol: BasePresenterViewProtocol {
    
    func getCurrrentWeather(lat: Double, lon: Double)
    func getBookmarks()
    func getBookmarksCount() -> Int
    func getBookmarkAt(index: Int) -> WeatherModel?
    func getLocationAt(index: Int) -> Location?
    func filterBookmarks(searchText: String)
    func deleteBookmark(index: Int)
}

protocol HomePresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func setCurrentWeather(currentWeather: WeatherModel)
    func getBookmarkWeathers(bookmarks: [Location])
    func addToBookmarkWeathers(weather: WeatherModel, index: Int)
}

protocol HomePresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol HomeInteractorProtocol: BaseInteractorProtocol {
    
    func getCurrrentWeather(lat: Double, lon: Double)
    func getBookmarks()
    func fetchBookmarkWeathers(bookmarks: [Location])
    func deleteLocation(location: Location)
}
