//
//  HomePresenter.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import Foundation

class HomePresenter: BasePresenter {
    
    // MARK: - Dependencies
    
    fileprivate var viewController: HomeViewControllerProtocol!
    fileprivate var interactor: HomeInteractorProtocol!
    fileprivate weak var delegate: HomePresenterDelegateProtocol?
    
    // MARK: - Extras
    
    // MARK: - Properties
    
    // MARK: - Initialization
    
    init(viewController: HomeViewControllerProtocol, interactor: HomeInteractorProtocol, delegate: HomePresenterDelegateProtocol?, extras: Any?) {
        self.viewController = viewController
        self.interactor = interactor
        self.delegate = delegate
        
        // Store extras
    }
    
    // MARK: - Business Logic
    
}

// MARK: - Extensions

// MARK: - Protocols Implemantations

// MARK: View Protocol

extension HomePresenter: HomePresenterViewProtocol {
    
    func getCurrrentWeather(lat: Double, lon: Double) {
        interactor.getCurrrentWeather(lat: lat, lon: lon)
    }
}

// MARK: Interactor Protocol

extension HomePresenter: HomePresenterInteractorProtocol {
    
    func setCurrentWeather(currentWeather: WeatherModel) {
        viewController.setCurrentWeatherLabel(currentWeather: currentWeather)
    }
}

// MARK: Delegate Protocol
