//
//  AddBookmarkViewController.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import UIKit
import MapKit
import CoreLocation

class AddBookmarkViewController: BaseViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var mapView: MKMapView!
    
    // MARK: - Dependencies
    
    var presenter: AddBookmarkPresenterViewProtocol!
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if CLLocationManager.locationServicesEnabled() {
            locationManager.delegate = self
            locationManager.desiredAccuracy = kCLLocationAccuracyBest
            locationManager.startUpdatingLocation()
            self.mapView.showsUserLocation = true
        }
    }
    
    // MARK: - Configure
    
    override func configureView() {
        super.configureView()
        
    }
    
    // MARK: - Initialization
    let locationManager: CLLocationManager = CLLocationManager()
    
    // MARK: - Actions
    
}

// MARK: - Extensions

// MARK: - Protocol Implemantations

extension AddBookmarkViewController: AddBookmarkViewControllerProtocol {
    
}

extension AddBookmarkViewController: CLLocationManagerDelegate {
    
}
