//
//  AddBookmarkProtocols.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import UIKit

// MARK: - View Controller

protocol AddBookmarkViewControllerProtocol: BaseViewControllerProtocol {
 
    func dismissView()
}

// MARK: - Presenter

protocol AddBookmarkPresenterViewProtocol: BasePresenterViewProtocol {
    
    func saveLocation(latitude: Double, longitude: Double)
}

protocol AddBookmarkPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    
    func dismissView()
}

protocol AddBookmarkPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor

protocol AddBookmarkInteractorProtocol: BaseInteractorProtocol {
    
    func saveLocation(latitude: Double, longitude: Double)
}
