//
//  AddBookmarkPresenter.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import Foundation

class AddBookmarkPresenter: BasePresenter {
    
    // MARK: - Dependencies
    
    fileprivate var viewController: AddBookmarkViewControllerProtocol!
    fileprivate var interactor: AddBookmarkInteractorProtocol!
    fileprivate var delegate: AddBookmarkPresenterDelegateProtocol?
    
    // MARK: - Extras
    
    // MARK: - Properties
    
    // MARK: - Initialization
    
    init(viewController: AddBookmarkViewControllerProtocol, interactor: AddBookmarkInteractorProtocol, delegate: AddBookmarkPresenterDelegateProtocol?, extras: Any?) {
        self.viewController = viewController
        self.interactor = interactor
        self.delegate = delegate
        
        // Store extras
    }
    
    // MARK: - Business Logic
    
}

// MARK: - Extensions

// MARK: - Protocols Implemantations

// MARK: View Protocol

extension AddBookmarkPresenter: AddBookmarkPresenterViewProtocol {
    
}

// MARK: Interactor Protocol

extension AddBookmarkPresenter: AddBookmarkPresenterInteractorProtocol {
    
}

// MARK: Delegate Protocol

