//
//  AddBookmarkWireframe.swift
//  Wheather App 2
//
//  Created by Mansur Muaz  Ekici on 16.07.2018.
//  Copyright (c) 2018 Adesso. All rights reserved.
//
//  Template generated by Zafer Caliskan

import UIKit

class AddBookmarkWireframe: BaseWireframe {
    
    func show(transitionType: WireframeTransitionType, delegate: AddBookmarkPresenterDelegateProtocol? = nil, extras: Any? = nil) {
        let viewController: AddBookmarkViewController = UIStoryboard.home.instantiateViewController()
        
        let interactor = AddBookmarkInteractor(coreDataService: CoreDataService.sharedInstance)
        
        let presenter = AddBookmarkPresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: viewController)
    }
    
}
