//
//  UIColorExtensions.swift
//  MACFit
//
//  Created Zafer Caliskan on 10/07/2017.
//  Copyright © 2017 marsathletic. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import UIKit

extension UIColor {

    class var adessoBackground: UIColor {
        return UIColor(white: 250.0 / 255.0, alpha: 1.0)
    }

    class var adessoBlack: UIColor {
        return UIColor(white: 0.0, alpha: 1.0)
    }

    class var adessoWhite: UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)
    }
    
    class var pieChartColors: [UIColor] {
        return [UIColor(red: 26/255, green: 71/255, blue: 149/255, alpha: 1),
         UIColor(red: 11/255, green: 82/255, blue: 178/255, alpha: 1),
         UIColor(red: 134/255, green: 59/255, blue: 140/255, alpha: 1),
         UIColor(red: 102/255, green: 26/255, blue: 108/255, alpha: 1),
         UIColor(red: 29/255, green: 183/255, blue: 175/255, alpha: 1),
         UIColor(red: 23/255, green: 156/255, blue: 149/255, alpha: 1)]
    }
    
}
