//
//  UITextViewExtensions.swift
//  MACFit
//
//  Created Zafer Caliskan on 10/07/2017.
//  Copyright © 2017 marsathletic. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import UIKit

extension ADSTextView {

    @IBInspectable var localizedString: String {
        set {
            text = newValue.storyboardLocalized
        }
        get {
            return localizedString
        }
    }
}
