//
//  UITextFieldExtensions.swift
//  MACFit
//
//  Created Zafer Caliskan on 10/07/2017.
//  Copyright © 2017 marsathletic. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import UIKit

extension ADSTextField {

    @IBInspectable var localizedString: String {
        set {
            text = newValue.storyboardLocalized
        }
        get {
            return self.localizedString
        }
    }

    @IBInspectable var localizedPlaceHolderString: String {
        set {
            placeholder = newValue.storyboardLocalized
        }
        get {
            return self.localizedPlaceHolderString
        }
    }
}
