//
//  UIViewControllerExtensions.swift
//  MACFit
//
//  Created Zafer Caliskan on 24/07/2017.
//  Copyright © 2017 marsathletic. All rights reserved.
//
//  Template generated by Zafer Caliskan
//

import UIKit

extension UIViewController {
    
    static func instantiateFromNib<VC: UIViewController>() -> VC {
        return VC(nibName: VC.className, bundle: nil)
    }
    
    func showSingleChoicePopup(popupType: ADSPopupType, title: String = "", message: String = "", doneTitle: String = "done".localized, completionHandler: ADSPopupCompletionHandler?) {
        let popupViewController: ADSPopupViewController = UIViewController.instantiateFromNib()
        popupViewController.modalPresentationStyle = .overCurrentContext
        popupViewController.modalTransitionStyle = .crossDissolve
        
        present(popupViewController, animated: true, completion: nil)
        
        popupViewController.showSingleChoice(popupType: popupType, title: title, message: message, doneTitle: doneTitle, completionHandler: completionHandler)
    }
    
    func showMultipleChoicePopup(popupType: ADSPopupType, title: String = "", message: String = "", yesTitle: String = "yes".localized, noTitle: String = "no".localized, completionHandler: ADSPopupCompletionHandler?) {
        let popupViewController: ADSPopupViewController = UIViewController.instantiateFromNib()
        popupViewController.modalPresentationStyle = .overCurrentContext
        popupViewController.modalTransitionStyle = .crossDissolve
        
        present(popupViewController, animated: true, completion: nil)
        
        popupViewController.showMultipleChoice(popupType: popupType, title: title, message: message, yesTitle: yesTitle, noTitle: noTitle, completionHandler: completionHandler)
    }
    
}
